default-target = "wasm32-unknown-emscripten"

[cargo-web]
minimum-version = "0.6.0"

[target.emscripten]
link-args = [
  "-s",
  "USE_SDL=2",
  "-s",
  "USE_SDL_IMAGE=2",
  "-s",
  "SDL2_IMAGE_FORMATS='['png']'",
  "-s",
  "MIN_WEBGL_VERSION=2",
  "-s",
  "MAX_WEBGL_VERSION=2",
  "--embed-file",
  "spritesheet.png",
  "--embed-file",
  "splashscreen.png",
  "--embed-file",
  "joshs_font.png",
]
